# Generated by Django 5.2.15 on 2026-10-06 13:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event')),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('venue', models.CharField(help_text='Location/venue of the event', max_length=300)),
                ('max_seats', models.IntegerField(help_text='Maximum number of seats available', validators=[django.core.validators.MinValueValidator(1)])),
                ('category', models.CharField(choices=[('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('conference', 'Conference'), ('meetup', 'Meetup'), ('competition', 'Competition')], default='hackathon', help_text='Category of the event', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='URL for event banner image', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the event is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['event_date'],
                'indexes': [models.Index(fields=['event_date'], name='idx_event_date'), models.Index(fields=['category'], name='idx_event_category'), models.Index(fields=['is_active'], name='idx_event_active')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the participant', max_length=200)),
                ('email', models.EmailField(help_text='Email address (unique identifier)', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=15)),
                ('college', models.CharField(blank=True, help_text='College/University name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'participants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['email'], name='idx_participant_email')],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(help_text='Foreign Key → Event table', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('participant', models.ForeignKey(help_text='Foreign Key → Participant table', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.participant')),
            ],
            options={
                'db_table': 'registrations',
                'ordering': ['-registered_at'],
                'indexes': [models.Index(fields=['event', 'participant'], name='idx_reg_event_participant')],
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
